name: Build Android

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: 'temurin'
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew assembleRelease
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          if-no-files-found: 'error'
          name: metrodroid-release-unsigned.apk.zip
          path: build/outputs/apk/release/metrodroid-release-unsigned.apk
